name: Build and publish server image

on:
  push:
    paths:
      - 'server/**'
  workflow_dispatch: {}

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/noormujassim-server:latest
